import "./globals.css";
import type { Metadata } from "next";

import Link from "next/link";
import { Inter } from "next/font/google";
import { Routes } from "../models";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>{children}</body>
    </html>
  );
}
